import Head from "next/head";
import Image from "next/image";
import Blog from "../Components/Blog/Blog";
import Footer from "../Components/Footer/Footer";
import Topmenu from "../Components/Topmenu/Topmenu";
import Navbar from "./../Components/Navbar/Navbar";

export default function blog() {
  return (
    <div>
      <Head>
        <title>Keyonavillie School | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topmenu />
      <Navbar />
      <Blog />
      <Footer />
    </div>
  );
}
