import Head from "next/head";
import Contact from "../Components/Contact/Contact";
import Footer from "./../Components/Footer/Footer";
import Navbar from "./../Components/Navbar/Navbar";
import OpenDays from "./../Components/OpenDays";
// import OpenDays from "../components/OpenDays";
import Topmenu from "../Components/Topmenu/Topmenu";

export default function contact() {
  return (
    <>
      <Head>
        <title>Keyonavillie School | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favblack.png" size="64X64" type="image/png" />
      </Head>
      <Topmenu />
      <Navbar />
      <Contact />
      <OpenDays />
      <Footer />
    </>
  );
}
