import Head from "next/head";
import Image from "next/image";
import Contact from "../Components/Contact/Contact";

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Keyonavillie School | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Contact />
      <h1>Contact Page</h1>
    </div>
  );
}
