import Head from "next/head";
import Image from "next/image";
import Navbar from "./../Components/Navbar/Navbar";
// import Faq from "./faq";
import Faq from "../Components/Faq/Faq";
import Footer from "./../Components/Footer/Footer";

export default function faq() {
  return (
    <div>
      <Head>
        <title>Keyonavillie School | Faq</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Faq />
      <h1>Faq Page</h1>
      <Footer />
    </div>
  );
}
