import Head from "next/head";
import Image from "next/image";
import Footer from "../Components/Footer/Footer";
import Navbar from "../Components/Navbar/Navbar";
import Gallery from "../Components/Gallery/Gallery";
import Topmenu from "./../Components/Topmenu/Topmenu";

export default function gallery() {
  return (
    <>
      <Head>
        <title>Keyonavillie School | Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favblack.png" size="64X64" type="image/png" />
      </Head>
      <Topmenu />
      <Navbar />
      <Gallery />
      <Footer />
    </>
  );
}
