import Head from "next/head";
import Image from "next/image";
import Footer from "../Components/Footer/Footer";
import Navbar from "../Components/Navbar/Navbar";

export default function Gallery() {
  return (
    <div>
      <Head>
        <title>Keyonavillie School | Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1>Gallery Page</h1>
      <Footer />
    </div>
  );
}
