import Head from "next/head";
import Image from "next/image";

export default function Gallery() {
  return (
    <div>
      <Head>
        <title>Keyonavillie School | Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Gallery Page</h1>
    </div>
  );
}
