import Head from 'next/head'
import Image from 'next/image'
import Footer from "../Components/Footer/Footer";
import Navbar from "../Components/Navbar/Navbar";
import Slider from "../Components/Slider/Slider";
import Testimonial from "../Components/Testimonial/testimonial";



export default function Home() {
  return (
    <div>
      <Head>
        <title>Keyonaville School | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Slider />
      <Testimonial />
      <h1>Home page</h1>
      <Footer />
    </div>
  );
}
